/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package psp.imap;//davidballester@paucasesnovescifp.cat

import java.io.UnsupportedEncodingException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Enumeration;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Flags;
import javax.mail.Folder;
import javax.mail.Header;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.internet.MimeBodyPart;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author angel y David
 */
public class MainForm extends javax.swing.JFrame {

    private String correosPath = "src/main/resources/correos"; //"D:\\Clases2\\SPPSP\\IMAP\\Imap\\src\\main\\resources\\correos";
    private File directorio = new File(correosPath);
    private DefaultListModel correosListModel = new DefaultListModel();

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecuperacionDeCorreos = new javax.swing.ButtonGroup();
        CopiaSeguridad = new javax.swing.ButtonGroup();
        Curso = new javax.swing.ButtonGroup();
        RolLOL = new javax.swing.ButtonGroup();
        COD = new javax.swing.ButtonGroup();
        Genero = new javax.swing.ButtonGroup();
        tabpnlCorreos = new javax.swing.JTabbedPane();
        pnlImap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaMensage = new javax.swing.JTextArea();
        btnReadCorreos = new javax.swing.JButton();
        lblTotalCorreos = new javax.swing.JLabel();
        prgCorreos = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCorreos = new javax.swing.JList<>();
        txtFileName = new javax.swing.JTextField();
        btnSelectFile = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblMails = new javax.swing.JLabel();
        lblFolder = new javax.swing.JLabel();
        pnlSmtp = new javax.swing.JPanel();
        lblRecuGustado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        rbtnRecuYes = new javax.swing.JRadioButton();
        rbtnRecuNo = new javax.swing.JRadioButton();
        lblCopiaSeguridad = new javax.swing.JLabel();
        rbtnAlMes = new javax.swing.JRadioButton();
        rbtnAlAny = new javax.swing.JRadioButton();
        rbtnNunca = new javax.swing.JRadioButton();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblPokeFav = new javax.swing.JLabel();
        txtPokeFav = new javax.swing.JTextField();
        lblCursoGustado = new javax.swing.JLabel();
        rbtnCursoYes = new javax.swing.JRadioButton();
        rbtnCursoNo = new javax.swing.JRadioButton();
        lblRolLOL = new javax.swing.JLabel();
        rbtnTop = new javax.swing.JRadioButton();
        rbtnJungle = new javax.swing.JRadioButton();
        rbtnAdc = new javax.swing.JRadioButton();
        rbtnMid = new javax.swing.JRadioButton();
        rbtnSupport = new javax.swing.JRadioButton();
        lblCOD = new javax.swing.JLabel();
        rbtnCompanya = new javax.swing.JRadioButton();
        rbtnMultijugador = new javax.swing.JRadioButton();
        rbtnZombies = new javax.swing.JRadioButton();
        lblGenero = new javax.swing.JLabel();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        rbtnHelicoptero = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txaMensage.setEditable(false);
        txaMensage.setColumns(20);
        txaMensage.setLineWrap(true);
        txaMensage.setRows(5);
        txaMensage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaMensage);

        btnReadCorreos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnReadCorreos.setText("Read");
        btnReadCorreos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadCorreosActionPerformed(evt);
            }
        });

        prgCorreos.setStringPainted(true);

        lstCorreos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCorreos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCorreosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCorreos);

        txtFileName.setEditable(false);
        txtFileName.setText("jTextField1");
        txtFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileNameActionPerformed(evt);
            }
        });

        btnSelectFile.setText("Select");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecFile(evt);
            }
        });

        lblMessage.setText("Message: ");

        lblMails.setText("Mails:");

        lblFolder.setText("Select folder to save mails:");

        javax.swing.GroupLayout pnlImapLayout = new javax.swing.GroupLayout(pnlImap);
        pnlImap.setLayout(pnlImapLayout);
        pnlImapLayout.setHorizontalGroup(
            pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImapLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMails)
                        .addComponent(lblTotalCorreos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prgCorreos, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMessage)
                    .addComponent(lblFolder)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImapLayout.createSequentialGroup()
                        .addComponent(txtFileName)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectFile))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(btnReadCorreos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImapLayout.setVerticalGroup(
            pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(lblMails))
                .addGap(5, 5, 5)
                .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlImapLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlImapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReadCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlImapLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(prgCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpnlCorreos.addTab("IMAP", pnlImap);

        lblRecuGustado.setText("<html><p width=150>Te ha gustado la recuperación de correos?</p></html>");

        lblNombre.setText("Cual es tu nombre?");

        RecuperacionDeCorreos.add(rbtnRecuYes);
        rbtnRecuYes.setText("Si");

        RecuperacionDeCorreos.add(rbtnRecuNo);
        rbtnRecuNo.setText("No");

        lblCopiaSeguridad.setText("<html><p width=175>Cada cuanto sueles hacer una copia de seguridad de tus correos?</p></html>");

        CopiaSeguridad.add(rbtnAlMes);
        rbtnAlMes.setText("Una vez al mes");

        CopiaSeguridad.add(rbtnAlAny);
        rbtnAlAny.setText("Una vez al año");

        CopiaSeguridad.add(rbtnNunca);
        rbtnNunca.setText("Nunca");

        lblCorreo.setText("Cual es tu correo?");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("jLabel1");

        lblPokeFav.setText("Cual es tu pokemon fav?");

        lblCursoGustado.setText("<html><p width=150>Te esta gustando este curso?</p></html>");

        Curso.add(rbtnCursoYes);
        rbtnCursoYes.setText("Si");

        Curso.add(rbtnCursoNo);
        rbtnCursoNo.setText("No");

        lblRolLOL.setText("<html><p width=150>Cual es tu rol fav en el LOL?</p></html>");

        RolLOL.add(rbtnTop);
        rbtnTop.setText("TOP");

        RolLOL.add(rbtnJungle);
        rbtnJungle.setText("JUNGLE");

        RolLOL.add(rbtnAdc);
        rbtnAdc.setText("ADC");

        RolLOL.add(rbtnMid);
        rbtnMid.setText("MID");

        RolLOL.add(rbtnSupport);
        rbtnSupport.setText("SUPPORT");

        lblCOD.setText("<html><p width=175>Que crees que es lo mejor de COD?</p></html>");

        COD.add(rbtnCompanya);
        rbtnCompanya.setText("Campaña");

        COD.add(rbtnMultijugador);
        rbtnMultijugador.setText("Multijugador");

        COD.add(rbtnZombies);
        rbtnZombies.setText("Zombies");

        lblGenero.setText("Cual es tu genero?");

        Genero.add(rbtnHombre);
        rbtnHombre.setText("Hombre");

        Genero.add(rbtnMujer);
        rbtnMujer.setText("Mujer");

        Genero.add(rbtnHelicoptero);
        rbtnHelicoptero.setText("Helicoptero de combate");

        javax.swing.GroupLayout pnlSmtpLayout = new javax.swing.GroupLayout(pnlSmtp);
        pnlSmtp.setLayout(pnlSmtpLayout);
        pnlSmtpLayout.setHorizontalGroup(
            pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSmtpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSmtpLayout.createSequentialGroup()
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCopiaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnAlMes)
                                    .addComponent(rbtnAlAny)
                                    .addComponent(rbtnNunca))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnRecuYes)
                                            .addComponent(rbtnRecuNo))
                                        .addGap(121, 121, 121))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSmtpLayout.createSequentialGroup()
                                        .addComponent(lblRecuGustado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))
                            .addGroup(pnlSmtpLayout.createSequentialGroup()
                                .addComponent(lblError)
                                .addGap(18, 18, 18)))
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCursoGustado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnCursoYes)
                            .addComponent(rbtnCursoNo))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSmtpLayout.createSequentialGroup()
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSmtpLayout.createSequentialGroup()
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre))
                                .addGap(39, 39, 39)
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreo))
                                .addGap(28, 28, 28)
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                                        .addComponent(txtPokeFav, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEnviar))
                                    .addComponent(lblPokeFav)))
                            .addGroup(pnlSmtpLayout.createSequentialGroup()
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRolLOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnMid)
                                            .addComponent(rbtnTop))
                                        .addGap(9, 9, 9)
                                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnAdc)
                                            .addComponent(rbtnJungle)))
                                    .addComponent(rbtnSupport))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnZombies)
                                    .addComponent(lblCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnCompanya)
                                    .addComponent(rbtnMultijugador))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnHelicoptero)
                                    .addComponent(lblGenero)
                                    .addComponent(rbtnHombre)
                                    .addComponent(rbtnMujer))))
                        .addContainerGap())))
        );
        pnlSmtpLayout.setVerticalGroup(
            pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSmtpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblError)
                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(rbtnCursoYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCursoNo))
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecuGustado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCursoGustado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnRecuYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnRecuNo))
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCopiaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAlMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAlAny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnNunca)))
                .addGap(30, 30, 30)
                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addComponent(lblRolLOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnTop)
                            .addComponent(rbtnAdc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnJungle)
                            .addComponent(rbtnMid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnSupport))
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnHombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMujer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnHelicoptero))
                    .addGroup(pnlSmtpLayout.createSequentialGroup()
                        .addComponent(lblCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCompanya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMultijugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnZombies)))
                .addGap(32, 32, 32)
                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCorreo)
                    .addComponent(lblPokeFav))
                .addGap(2, 2, 2)
                .addGroup(pnlSmtpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPokeFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addContainerGap())
        );

        tabpnlCorreos.addTab("SMTP", pnlSmtp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpnlCorreos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpnlCorreos)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadCorreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadCorreosActionPerformed
        correosListModel.clear();
        lstCorreos.setModel(correosListModel);
        Thread readEmailsThread = new Thread(new HiloCorreos(lblTotalCorreos, correosPath, prgCorreos, btnSelectFile, btnReadCorreos, directorio, correosListModel, lstCorreos));
        readEmailsThread.start();
        btnSelectFile.setEnabled(false);
        btnReadCorreos.setEnabled(false);
    }//GEN-LAST:event_btnReadCorreosActionPerformed

    private void lstCorreosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCorreosValueChanged
        if (!(lstCorreos.getSelectedValue() == null || lstCorreos.getSelectedValue().isBlank() || lstCorreos.getSelectedValue().isEmpty())) {
            String selectedEmail = lstCorreos.getSelectedValue();
            txaMensage.setText("");
            for(File f : directorio.listFiles()){
                if(f.getName().equals(selectedEmail)){
                    BufferedReader reader = null;
                    try {
                        reader = new BufferedReader(new FileReader(f.getAbsolutePath()));
                        String line;
                        while((line = reader.readLine()) != null){
                            txaMensage.append(line + System.lineSeparator());;
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            reader.close();
                        } catch (IOException ex) {
                            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_lstCorreosValueChanged

    private void btnSelecFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecFile
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
            txtFileName.setText(fileChooser.getSelectedFile().getAbsolutePath());
            correosPath = fileChooser.getSelectedFile().getAbsolutePath();
            directorio = new File(correosPath);
        }
    }//GEN-LAST:event_btnSelecFile

    private void txtFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtFileName.setText(correosPath);
    }//GEN-LAST:event_formWindowOpened

    

   /* public void leerCorreos() throws MessagingException, IOException {
        cargarLista();
        Folder folder = null;
        Store store = null;
        try {
            Properties properties = new Properties();

            // server setting
            properties.put("mail.imap.host", "imap.gmail.com");
            properties.put("mail.imap.port", "993");

            // SSL setting
            properties.setProperty("mail.imap.socketFactory.class",
                    "javax.net.ssl.SSLSocketFactory");
            properties.setProperty("mail.imap.socketFactory.fallback",
                    "false");
            properties.setProperty("mail.imap.socketFactory.port",
                    String.valueOf(993));

            properties.setProperty("mail.store.protocol", "imaps");

            Session session = Session.getDefaultInstance(properties);
            store = session.getStore("imaps");
            store.connect("imap.gmail.com", "pruebaspsp111@gmail.com", "pspimap123");
            folder = store.getFolder("Inbox");

            folder.open(Folder.READ_WRITE);
            Message messages[] = folder.getMessages();
            int total = folder.getMessageCount();
            lblTotalCorreos.setText("Número total de mensages: " + total);
            //System.out.println("No of Unread Messages : " + folder.getUnreadMessageCount());
            for (int i = 0; i < messages.length; ++i) {

                Message msg = messages[i];
                
                //if we don''t want to fetch messages already processed
        
                if (!msg.isSet(Flags.Flag.SEEN)) {
                    Enumeration headers = messages[i].getAllHeaders();
                    while (headers.hasMoreElements()) {
                        Header h = (Header) headers.nextElement();
                        System.out.println(h.getName() + ": " + h.getValue());
                    }
                    System.out.println();
  
                    System.out.println("MESSAGE #" + (i + 1) + ":");
                    String from = "unknown";
                    System.out.println(msg.getHeader("Content-type"));
                    System.out.println(msg.getHeader("format"));
                    System.out.println(msg.getHeader("Content-Transfer-Encoding"));
                    if (msg.getReplyTo().length >= 1) {
                        from = msg.getReplyTo()[0].toString();
                    } else if (msg.getFrom().length >= 1) {
                        from = msg.getFrom()[0].toString();
                    }
                    String subject = msg.getSubject();
                    //System.out.println("Saving ... " + subject +" " + from);
                    // you may want to replace the spaces with "_"
                    // the TEMP directory is used to store the files
                    String filename = correosPath + "/" + subject;
                    saveParts(msg.getContent(), filename, subject);

                    msg.setFlag(Flags.Flag.SEEN, true);

                    
                    // to delete the message
                    // msg.setFlag(Flags.Flag.DELETED, true);
                } else {

                    System.out.println("MESSAGE #" + (i + 1) + ":" + " is already saved.");

                    String subject = msg.getSubject();
                }
                prgCorreos.setValue((i + 1) * prgCorreos.getMaximum() / (total));
            }
            btnSelectFile.setEnabled(true);
            btnReadCorreos.setEnabled(true);

        } finally {
            if (folder != null) {
                folder.close(true);
            }
            if (store != null) {
                store.close();
            }
        }
    }

    public void saveParts(Object content, String filename, String subject) throws IOException, MessagingException {
        OutputStream out = null;
        InputStream in = null;
        try {
            if (content instanceof Multipart) {
                Multipart multi = ((Multipart) content);
                int parts = multi.getCount();
                for (int j = 0; j < parts; ++j) {
                    MimeBodyPart part = (MimeBodyPart) multi.getBodyPart(j);
                    if (part.getContent() instanceof Multipart) {
                        // part-within-a-part, do some recursion...
                        saveParts(part.getContent(), filename, subject);
                    } else {
                        String extension = "";
                        if (part.isMimeType("text/html")) {
                            extension = "html";
                        } else {
                            if (part.isMimeType("text/plain")) {
                                extension = "txt";
                            } else {
                                //  Try to get the name of the attachment
                                extension = part.getDataHandler().getName();
                            }
                            filename = filename + "." + extension;
                            System.out.println("... " + filename);
                            //cargarLista();
                            //con esto el .txt.null no se pone y no se puede leer, mejor sera cargarlista de 0 aunque tarde mas? idk
                            correosListModel.addElement(subject + "." + extension);
                            lstCorreos.setModel(correosListModel);
                            out = new FileOutputStream(new File(filename), true);
                            in = part.getInputStream();
                            int k;
                            while ((k = in.read()) != -1) {
                                out.write(k);
                            }
                        }
                    }
                }
            }
        } finally {
            if (in != null) {
                in.close();
            }
            if (out != null) {
                out.flush();
                out.close();
            }
        }
    }

    public void cargarLista() {
        //correosListModel.clear();
        for (String s : directorio.list()) {
            correosListModel.addElement(s);
        }
        lstCorreos.setModel(correosListModel);
    }
    */
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        Pattern comprobante = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher matcher = comprobante.matcher(txtCorreo.getText());

        if ((rbtnJungle.isSelected() || rbtnMid.isSelected() || rbtnTop.isSelected() || rbtnSupport.isSelected() || rbtnAdc.isSelected())
            && (rbtnCompanya.isSelected() || rbtnZombies.isSelected() || rbtnMultijugador.isSelected())
            && (rbtnHombre.isSelected() || rbtnMujer.isSelected() || rbtnHelicoptero.isSelected())
            && (rbtnAlMes.isSelected() || rbtnAlAny.isSelected() || rbtnNunca.isSelected())
            && (rbtnCursoYes.isSelected() || rbtnCursoNo.isSelected())
            && (rbtnRecuYes.isSelected() || rbtnRecuNo.isSelected())
            && !txtPokeFav.getText().isBlank() && !txtPokeFav.getText().isEmpty()
            && !txtNombre.getText().isBlank() && !txtNombre.getText().isEmpty()
            && !txtCorreo.getText().isBlank() && !txtCorreo.getText().isEmpty()) {

            if (matcher.find() == true) {
                lblError.setVisible(false);
                lblError.setText("");

                Properties prop = new Properties();
                prop.put("mail.smtp.host", "smtp.gmail.com");
                prop.put("mail.smtp.port", "465");
                prop.put("mail.smtp.auth", "true");
                prop.put("mail.smtp.socketFactory.port", "465");
                prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

                Session session = Session.getInstance(prop,
                    new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {//pruebaspsp111@gmail.com
                            return new PasswordAuthentication("pruebaspsp111@gmail.com", "pspimap123");
                        }
                    });

                    try {

                        MimeMessage message = new MimeMessage(session);

                        //Message message = new MimeMessage(session);

                        //message.setHeader("MIME-Version", "1.0");
                        message.setHeader("Content-Type", "multipart/alternative; boundary=\"000000000000319cdd05d78693c5\"");
                        //message.addHeader("Content-type", "text/HTML; charset=UTF-8");
                        //message.addHeader("format", "flowed");
                        //message.addHeader("Content-Transfer-Encoding", null);
                        message.removeHeader("Content-Transfer-Encoding");
                        //message.getAllHeaders();

                        InternetAddress ia = new InternetAddress();
                        ia.setAddress("pruebaspsp111@gmail.com");
                        ia.setPersonal("pruebas psp");
                        message.setFrom(ia);
                        //message.setReplyTo(InternetAddress.parse("pruebaspsp111@gmail.com"));
                        /*
                        Content-Type: text/plain; charset="iso-2022-jp"
                        Content-Transfer-Encoding: 7bit
                        Content-Disposition: inline; filename="test.txt"
                        */

                        message.setRecipients(
                            Message.RecipientType.TO,
                            InternetAddress.parse("pruebaspsp111@gmail.com, " + txtCorreo.getText())
                        );
                        //String kjasd = "alkjsd";
                        message.setSubject(txtNombre.getText());
                        //message.setText("SEXOOOOOO PLS", "text/html");
                        
                        String tiempoCopiaSeguridad = "";
                        String recuGustado = "";
                        String cursoGustado = "";
                        String rolLOL = "";
                        String modoCOD = "";
                        String genero = "";
                        
                        if(rbtnAlAny.isSelected())
                            tiempoCopiaSeguridad = rbtnAlAny.getText();
                        else if(rbtnAlMes.isSelected())
                            tiempoCopiaSeguridad = rbtnAlMes.getText();
                        else
                            tiempoCopiaSeguridad = rbtnNunca.getText();

                        if(rbtnRecuYes.isSelected())
                            recuGustado = rbtnRecuYes.getText();
                        else
                            recuGustado = rbtnRecuNo.getText();
                        
                        if(rbtnCursoYes.isSelected())
                            cursoGustado = rbtnCursoYes.getText();
                        else
                            cursoGustado = rbtnCursoNo.getText();
                        
                        if(rbtnSupport.isSelected())
                            rolLOL = rbtnSupport.getText();
                        else if(rbtnJungle.isSelected())
                            rolLOL = rbtnJungle.getText();
                        else if(rbtnMid.isSelected())
                            rolLOL = rbtnMid.getText();
                        else if(rbtnAdc.isSelected())
                            rolLOL = rbtnAdc.getText();
                        else
                            rolLOL = rbtnTop.getText();
                        
                        if(rbtnCompanya.isSelected())
                            modoCOD = rbtnCompanya.getText();
                        else if(rbtnMultijugador.isSelected())
                            modoCOD = rbtnMultijugador.getText();
                        else
                            modoCOD = rbtnZombies.getText();
                        
                        if(rbtnHombre.isSelected())
                            genero = rbtnHombre.getText();
                        else if(rbtnMujer.isSelected())
                            genero = rbtnMujer.getText();
                        else
                            genero = rbtnHelicoptero.getText();

                        message.setText("Cada cuanto sueles hacer una copia de seguridad de tus correos?" + "\n" + tiempoCopiaSeguridad + "\n\n"
                            + "Te ha gustado la recuperación de correos?" + "\n" + recuGustado + "\n\n" 
                                + "Te esta gustando este curso?" + "\n" + cursoGustado + "\n\n" 
                                + "Cual es tu rol fav en el LOL?" + "\n" + rolLOL + "\n\n" 
                                + "Que crees que es lo mejor de COD?" + "\n" + modoCOD + "\n\n"
                                + "Cual es tu genero?" + "\n" + genero + "\n\n"
                                + "Cual es tu pokemon fav?" + "\n" + txtPokeFav.getText() + "\n\n");

                        /*message.setContent(
                            "<h1>This is actual message embedded in HTML tags</h1>",
                            "text/html");*/

                        Transport.send(message);
                        System.out.println("Done");
                    } catch (MessagingException e) {
                        e.printStackTrace();
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else {
                    lblError.setVisible(true);
                    lblError.setText("Por favor, ponga bien el correo.");
                }
            } else {
                lblError.setVisible(true);
                lblError.setText("Por favor, rellene todos los datos.");
            }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup COD;
    private javax.swing.ButtonGroup CopiaSeguridad;
    private javax.swing.ButtonGroup Curso;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.ButtonGroup RecuperacionDeCorreos;
    private javax.swing.ButtonGroup RolLOL;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnReadCorreos;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCOD;
    private javax.swing.JLabel lblCopiaSeguridad;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCursoGustado;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFolder;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMails;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPokeFav;
    private javax.swing.JLabel lblRecuGustado;
    private javax.swing.JLabel lblRolLOL;
    private javax.swing.JLabel lblTotalCorreos;
    private javax.swing.JList<String> lstCorreos;
    private javax.swing.JPanel pnlImap;
    private javax.swing.JPanel pnlSmtp;
    private javax.swing.JProgressBar prgCorreos;
    private javax.swing.JRadioButton rbtnAdc;
    private javax.swing.JRadioButton rbtnAlAny;
    private javax.swing.JRadioButton rbtnAlMes;
    private javax.swing.JRadioButton rbtnCompanya;
    private javax.swing.JRadioButton rbtnCursoNo;
    private javax.swing.JRadioButton rbtnCursoYes;
    private javax.swing.JRadioButton rbtnHelicoptero;
    private javax.swing.JRadioButton rbtnHombre;
    private javax.swing.JRadioButton rbtnJungle;
    private javax.swing.JRadioButton rbtnMid;
    private javax.swing.JRadioButton rbtnMujer;
    private javax.swing.JRadioButton rbtnMultijugador;
    private javax.swing.JRadioButton rbtnNunca;
    private javax.swing.JRadioButton rbtnRecuNo;
    private javax.swing.JRadioButton rbtnRecuYes;
    private javax.swing.JRadioButton rbtnSupport;
    private javax.swing.JRadioButton rbtnTop;
    private javax.swing.JRadioButton rbtnZombies;
    private javax.swing.JTabbedPane tabpnlCorreos;
    private javax.swing.JTextArea txaMensage;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPokeFav;
    // End of variables declaration//GEN-END:variables

}
